version: "3"
services:
  ark:
    image: motey/arkserver
    restart: unless-stopped
    ports:
      - 7776:7776/udp
      - 7776:7776
      - 7777:7777/udp
      - 7777:7777
      - 7778:7778/udp
      - 7778:7778
      - 27014:27014/udp
      - 27014:27014
      - 27015:27015/udp
      - 27015:27015
      - 27016:27016/udp
      - 27016:27016
      - 32330:32330
    environment:
      - SERVERMAP=TheIsland
      - SESSIONNAME=NewGaeArk
      - ADMINPASSWORD=#OMITTED
      - SERVERPASSWORD=#OMITTED
      - SERVERPORT=27015
      - STEAMPORT=7778
      - WARNONSTOP=1
      - UID=1000
      - GID=1000
      - TZ=Europe/Dublin
    volumes:
      - /root/ark/ark:/ark
      - /root/OneDrive/Servers/Ark:/ark/backup