version: "3"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      ENABLE_COMMAND_BLOCK: "true"
      VIEW_DISTANCE: 16
      MEMORY: "6G"
      ENABLE_WHITELIST: "true"
      ENFORCE_WHITELIST: "true"
      MOTD: "§l§cJesse's§r Dockerised Minecraft server!"
      OVERRIDE_ICON: "true"
      OVERRIDE_SERVER_PROPERTIES: "true"
      ICON: "/data/emoji.png"
      ENABLE_RCON: "true"
      RCON_PASSWORD: #OMITTED
      RCON_HOST: #OMITTED
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - /root/minecraft/data:/data:rw
  backup:
    image: itzg/mc-backup
    environment:
      BACKUP_INTERVAL: "1d" 
      PAUSE_IF_NO_PLAYERS: "true"
      TAR_COMPRESS_METHOD: "gzip"
      RCON_PASSWORD: #OMITTED
      INITIAL_DELAY: "1m"
    volumes:
      - /root/minecraft/data:/data:ro
      - /root/OneDrive/Servers/Minecraft/Dockerised:/backups:rw
    restart: unless-stopped
    network_mode: "service:mc"