version: "2"
services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex
    environment:
      - VERSION=docker
      - PLEX_CLAIM
    volumes:
      - ~/docker-services/plex/config:/config
      - ~/media:/mnt
    ports:
      - 32400:32400
    restart: unless-stopped

  transmission:
    cap_add:
      - NET_ADMIN
    image: haugene/transmission-openvpn
    environment:
      - TZ=Europe/London
      - TRANSMISSION_RPC_USERNAME=#OMITTED
      - TRANSMISSION_RPC_PASSWORD=#OMITTED
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=netherlands,sweden,france
      - OPENVPN_USERNAME=#OMITTED
      - OPENVPN_PASSWORD=#OMITTED
      - TRANSMISSION_WEB_UI=flood-for-transmission
      - LOCAL_NETWORK=10.6.0.0/16
    volumes:
      - ~/docker-services/transmission/config:/config
      - ~/docker-services/transmission/data:/data
      - ~/media:/mnt/media
      - ~/media/downloads:/downloads
    ports:
      - 9091:9091
      - 49153:49153
      - 49153:49153/udp
    restart: unless-stopped

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - TZ=Europe/London
    volumes:
      - ~/docker-services/jackett/config:/config
      - ~/media/downloads/complete:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - ~/docker-services/transmission/data:/data
      - ~/docker-services/sonarr/config:/config
      - ~/media:/mnt/media
      - ~/media/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - TZ=Europe/London
    volumes:
      - ~/docker-services/transmission/data:/data
      - ~/docker-services/radarr/config:/config
      - ~/media:/mnt/media
      - ~/media/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  ombi:
    image: ghcr.io/linuxserver/ombi
    container_name: ombi
    environment:
      - TZ=Europe/London
      - BASE_URL=/ombi #optional
    volumes:
      - ~/docker-services/ombi/config:/config
    ports:
      - 3579:3579
    restart: unless-stopped

  tautulli:
    image: tautulli/tautulli
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - ~/docker-services/tautulli/config:/config
    environment:
      - TZ=Europe/London
    ports:
      - 8181:8181